In [1]:
import os
os.chdir(r"D:\Ritwik's Download\Innomatics Research Lab\mlflow")

In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv("D:\Ritwik's Download\Data Analysis\ChurnData.csv")
df

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0       4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1       9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2       6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3       6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4       7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   
..       ...  ...    ...       ...       ...     ...    ...      ...      ...   
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
0    4.913      4.0    1.0  
1    3.497      1.0    1.0  
2    3.401      3.0    0.0  
3    4.331      4.0    0.0  
4    4.382      3.0    0.0  
..     ...      ...    ...  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[200 rows x 28 columns]

In [9]:
df = df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
df['churn'] = df['churn'].astype('int')
df.head()

C:\Users\RITWIK~1\AppData\Local\Temp/ipykernel_14144/3117518973.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['churn'] = df['churn'].astype('int')


tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

In [10]:
X = np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [11]:
y = np.asarray(df['churn'])
y [0:5]

array([1, 1, 0, 0, 0])

In [12]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 7) (160,)
Test set: (40, 7) (40,)


In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [15]:
yhat = LR.predict(X_test)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0])

In [19]:
from sklearn.metrics import classification_report, accuracy_score
print(classification_report(yhat, y_test))

              precision    recall  f1-score   support

           0       0.96      0.73      0.83        33
           1       0.40      0.86      0.55         7

    accuracy                           0.75        40
   macro avg       0.68      0.79      0.69        40
weighted avg       0.86      0.75      0.78        40



In [ ]:
! pip install mlflow